### ISSUE TITLE
[문의] Framework 사용 관련 문의

### ISSUE THREAD

**Issue by seong0905** [DatathonInfo/MISOChallenge-pet#3]
![image](https://user-images.githubusercontent.com/70629496/141732803-7d7da94a-ae5d-4af5-a2fc-c231d4ba779d.png)

대회 설명서를 읽어보니, 제출 파일이 모두 baseline 코드에서 생성되는 파일들인 것 같습니다.
또한 test코드 또한 baseline의 형식을 유지해야 하는 것 같은데, 
저희 팀 대부분이 pytorch에 더 익숙하여 baseline의 형식을 유지한다면 다양한 실험이 어려울 것 같습니다.
혹시 제출 파일의 csv, png 등 형식을 유지한다면 pytorch를 이용한 테스트 코드와 모델 파일로 제출이 가능할까요?

**Comment by two4zero** [comment]
안녕하세요. @seong0905 
문의하신 내용에 대하여 검토 중입니다.
감사합니다.

**Comment by DatathonInfo** [comment]
안녕하세요.
seong0905 님.

질문 주신 pytorch를 이용한 테스트 코드와 모델 파일 제출 가능 여부에 대해서 내부적으로 확인 한 결과
제출 파일의 csv, png 등의 형식이 유지가 된다면 pytorch를 이용하셔도 되고, 모델 및 결과값을 따로 제출해주시면 됩니다.
pytorch 1.2.0버전을 권장하며, 평가사 측에서 코드 재현 했을 때 코드 동작의 불가함에 따른 불이익이 발생 할 수 있습니다.


감사합니다.
2021 미소 인공지능 모델 개발 챌린지 운영팀.

**Comment by seong0905** [comment]
감사합니다!
