### ISSUE TITLE
NSML 로그인 이슈 확인부탁드립니다. 

### ISSUE THREAD

**Issue by jiwoo-coding** [DatathonInfo/MISOChallenge-pet#5]
팀명 : 아이리포
Git ID : hjahn1210@naver.com
이름 : 안효지
이외 팀 전원 GIT ID 확인 부탁드립니다.

**Comment by DatathonInfo** [comment]
안녕하세요. 

참가자님

확인 요청주신 팀원 Github(NSML) 계정 첨부드립니다.

팀리더: Hyoji-Ahn
팀원1: minyoung2123
팀원2: 2m1ns00
팀원3: DrunkJin
팀원4: jiwoo-coding

입니다. 

감사합니다. 

2021 미소 인공지능 모델 개발 챌린지 운영팀

**Comment by jiwoo-coding** [comment]
안녕하세요.

현재 위와같은 ID로 로그인 시도를 했으나 지속적으로 
You are not a registered user 오류가 발생하고 있습니다.

혹시 등록이 안되어있는지 확인 부탁드립니다.

실제 깃허브 홈페이지에서 아이디와 패스워드 입력하면 접속되나 NSML에서는 접속되지 않습니다.

**Comment by jiwoo-coding** [comment]
안녕하세요.

현재 위와같은 ID로 로그인 시도를 했으나 지속적으로 
You are not a registered user 오류가 발생하고 있습니다.

혹시 등록이 안되어있는지 확인 부탁드립니다.

실제 깃허브 홈페이지에서 아이디와 패스워드 입력하면 접속되나 NSML에서는 접속되지 않습니다.

**Comment by DatathonInfo** [comment]
안녕하세요.

참가자님

본 대회는 NSML이 아닌 Naver Cloud GPU 환경에서 진행되고 있습니다.

감사합니다.
