### ISSUE TITLE
[문의] eye data label관련 문의

### ISSUE THREAD

**Issue by K-nowing** [DatathonInfo/MISOChallenge-pet#6]
4가지 질환에 대해 질환 유무가 다 따로 labeling 되어 총 9개의 class가 나뉘어져 한 모델로 학습이 되는 것을 확인하였습니다.
 여기서 드는 의문이 만약에 4개지 질환에서 모두 정상인 안구 사진이 input으로 주어지면 정상 class가 총 4가지(안검내반증이 정상이다, 유루증이 정상이다, 백내장이 정상이다, 결막염이 정상이다) 모든 곳에 해당되는 input일 텐데, 레이블이 나눠지는 방식이 이게 맞는 것인지 의문이 들어 문의 남깁니다.
 마찬가지로 네가지 질환들이 중복으로 나타나는 데이터는 없는지도 궁금합니다.

**Comment by DatathonInfo** [comment]
안녕하세요.
K-nowing 님

질문 주신 레이블이 나눠지는 방식과 질환별 중복 데이터 유무  확인결과,
 경진대회에 사용된 데이터셋 중 안구질환 이미지는 복합 질환이 라벨링 되어 있지 않습니다. 예를 들어, 안검내반증에 있는 이미지도 결막염이 동시에 나타날 수 있습니다. 질환별 개별 검증으로 레이블이 나뉘어져있으며, 각각 독립적인 모델을 만들어주셔야합니다. 

감사합니다.
2021 미소 인공지능 모델 개발 첼린지 운영팀
